### PR TITLE
New SHAS intake skeleton

### PR DESCRIPTION
**Pull request by kyle1morel**
# Description

Implements the skeleton + basic form functionality for the new intake form. This form is designed to eventually fully replace the existing CHEFS SHAS intake form. Advanced functionality such as 3rd party API lookups, mapping, document upload, etc., is missing and scheduled to be done in the future.

58babb3 Update + Add unit tests
124850f Intake submit & confirmation
ea48354 Add fourth step - Permits
7981cbd Add third step - Location
815d192 Added second step - Housing
08f70bb Finalized styling. Added custom Stepper header and navigation components
aa923d4 New intake form - styling & first step

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have checked that unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by wilwong89** [comment]
`SubmissionForm.vue` is still using the boolean checkboxes for fields like `financiallySupported` and `financiallySupportedBC` that were converted to Yes/No/Unsure. Can't save the submission if those converted fields are checked off.

**Review by wilwong89 — APPROVED** [review]

**Comment by slhurley** [comment]
- Need help text outside of the field entry on the comma-separated PIDs field (or consistent help text/hints on fields)
- When entering the "Search the address" field it leaves it there shouldn't it disappear after it does the search (presumably this is coming with the validation layer)
- What is Locality?  Shouldn't it say City? (I could be wrong but never heard of this)
- "Provide a coordinate" has the word coordinate spelled wrong
- Can we make sure validation also chokes if you don't enter BC in the province?  Or perhaps just don't let them change this field?
- Spatial file is misspelled
- Need to get missing hints and missing X business days on the confirmation from Subin
- I think we need to remove the New vs. Applied permit status.  Either a proponent has applied or they haven't.

**Comment by Subin1Doo** [comment]
UI updates:
Housing tab
- in first section "Provide additional information" - change the font and color - same as all the other - not bolded
- still missing the upload document design that goes under provide additional information text box.

- type of residential multi select check boxes - when checked off should be the same color as radio buttons? 
- get rid of "?" next to Is this project being financially supported by any of the following
- BC Housing - "?" bubble should say: BC Housing welcomes the opportunity to work with individuals and organizations to create affordable housing solutions. 
- the word BC Housing in text bubble - hyperlinked to https://www.bchousing.org/proejcts-partners/partner-with-us
- "?" next to BC Housing not centre aligned, move up a little bit

- Change the font color for BC Housing, Indigenous Housing Provider, Non-profit housing society, Housing co-operative, so it's the not the same color as yes/no/unsure. 

Location tab
- get rid of "?" next to provide additional location details

**Comment by Subin1Doo** [comment]
Confirmation page message change to: Your submission will be reviewed by a Housing Navigator. You may be contacted if needed. Please check your email for the confirmation email and keep the confirmation ID for future reference.

**Comment by Subin1Doo** [comment]
For this: type of residential multi select check boxes - when checked off should be the same color as radio buttons?
I meant to change the color of the multi-select check boxes to that light sky blue-ish we were using for all radio buttons. 
Can we change it back to that color for all radio/ multi-select buttons? 

The question mark next to "provide additional information" isn't centre-aligned

for the BC housing hyperlink - can we hyperlink the word BC Housing on the actual form then? not the one inside the tooltip text.

Thank you!

**Comment by Subin1Doo** [comment]
Hyperlinks:
Indigenous housing provider:
https://www.bchousing.org/housing-assistance/rental-housing/indigenous-housing-providers
Non-profit housing society:
https://bcnpha.ca/member-programs-list/
housing co-operative:
https://www.chf.bc.ca/find-co-op/

For spatial file upload 
"see acceptable file formats": 
https://portal.nrs.gov.bc.ca/documents/10184/0/SpatialFileFormats.pdf/39b29b91-d2a7-b8d1-af1b-7216f8db38b4

One last thing.. 
For "Select all provincially issued permits you think you might need (optional)"
Can we make the length of the drop down for permits longer so it's the same as how it is for "Have you applied for any provincial permits for this project?"section.

Thank you!!

**Comment by Subin1Doo** [comment]
Hey Kyle, 
looks like we have to had another question / section to the form.
On the location tab - at the very top of the page add a new section
"Has the location of the project been affected by natural disaster?"
Yes / no radio button

**Comment by Subin1Doo** [comment]
Hey Kyle,
looks like we have to had another question / section to the form.
On the location tab - at the very top of the page add a new section
"Has the location of the project been affected by natural disaster?"
Yes / no radio button

Also, based on everyone's feedback we want to move the notice of collection message to the first page of the form, top of basic info tab. Check link below to see update on this:
https://www.figma.com/design/MOKpr9Jfu4ptlATQ23lFUf/SHAS?node-id=597%3A3896&t=xloJnti3d5zuClA9-1

Thank you!

**Comment by Subin1Doo** [comment]
Reminder to add labels to all dropdown/ type fields for accessibility. Thank you!

**Comment by Subin1Doo** [comment]
In the Location tab, below the street address / coordinates section, add another section labeled as "Is there anything else you would like to tell us about this projects location?" with a free text box. This section is optional.

Thank you!

**Pull request closed without merging**
