### PR TITLE
Submission information tab redesign

### PR DESCRIPTION
**Pull request by kyle1morel**
# Description

Realigns the Submission information tab with the new design.
Realigns constants and enums in both front and back end
Updated front and back end validators
Moved `contact_name` to `contact_first_name` and `contact_last_name`
New search submissions endpoint

5c805af Update CODEOWNERS
da33d47 Add new endpoint to search submissions
bad860c readonly store states
799cafc Set default submission type on intake
5efa3e5 Add manual migration script for contact first/last name updates
4d41631 Update unit tests
f1a3598 Fix contact names. Updates to submission types
33e75c7 Resolve issue creating empty Submission
68a633f Backend enum/constant realignment. Submission validation arealignment
599ec09 Frontend enum/constant realignment
6ce9f4d Form and validator realignment

https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-155

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have checked that unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by slhurley** [comment]
- Contact name info is not saving on list view or new sub view...I think you might have said this was coming.  
- Address field needs the locality/province added on both the new sub view and the list view still

**Comment by Subin1Doo** [comment]
UI looks good to me!
Not sure if it's already done, but submission type for all new submissions will automatically have to be set to "guidance." NAVs would only touch that field if it has to be changed to inapplicable. 
Thanks!

**Comment by Subin1Doo** [comment]
I will check with the NAVs tomorrow about their thoughts on not being able to edit the address field and how we want to display related enquiry submissions if there are multiple.

**Comment by kyle1morel** [comment]
> * Contact name info is not saving on list view or new sub view...I think you might have said this was coming.
> * Address field needs the locality/province added on both the new sub view and the list view still

Resolved


> UI looks good to me! Not sure if it's already done, but submission type for all new submissions will automatically have to be set to "guidance." NAVs would only touch that field if it has to be changed to inapplicable. Thanks!

Added this in

**Comment by Subin1Doo** [comment]
Related enquiry field: They are okay with displaying all related enquiry submissions by separating it with commas. Doesn't matter if one of the related enquiry is marked as complete, they'd like to see all that's related. I think it'd make most sense to display them in order of submission date (most recent ~)  when there are multiple.

**Comment by wilwong89** [comment]
For `SubmissionForm.vue`:
Cannot type in `companyNameRegistered` field, it empties itself when blurred.
FE validation for `singleFamilyUnits` seems to be triggering for required even when schema says not required. (Happens when blank)

**Review by sanjaytkbabu — APPROVED** [review]

**Review by wilwong89 — APPROVED** [review]

**Comment by Subin1Doo** [comment]
I just noticed the banner doesn't show up when the project submission has a related enquiry. Enquiry information tab shows the banner message with hyperlinked activity ID. This was a part of the other ticket "related submission" from before.. 🥲

**Pull request merged**
