### PR TITLE
UI Text Updates

### PR DESCRIPTION
**Pull request by sanjaytkbabu**
# Description
[PADS-279](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-279)
Text updates, refer the ticket for exhaustive list

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have checked that unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by slhurley** [comment]
- When submitting an Enquiry, the link still says back to home page on the confirmation and it should be back to Housing AND go to the menu page. On the confirmation page for Submissions, “Go to homepage” hyperlink now says “Back to Housing” but it isn't going to the menu button page.
- On the Enquiries tab of the "My drafts..." page the column header needs to also change from Activity to Confirmation ID.
- The status tracker still needs to be hidden from the Proponent role on both menus.

**Comment by Subin1Doo** [comment]
Check the wireframe for title on each form- font size is H1. Thank you!

**Comment by sanjaytkbabu** [comment]
> Confirmation message page for intake form, Back to Housing hyperlink takes user to the home page (landing page), should take them to the Housing page with three buttons. Check the wireframe for title on each form- font size is H1. Thank you!

done

**Comment by sanjaytkbabu** [comment]
> * When submitting an Enquiry, the link still says back to home page on the confirmation and it should be back to Housing AND go to the menu page. On the confirmation page for Submissions, “Go to homepage” hyperlink now says “Back to Housing” but it isn't going to the menu button page.
> * On the Enquiries tab of the "My drafts..." page the column header needs to also change from Activity to Confirmation ID.
> * The status tracker still needs to be hidden from the Proponent role on both menus.

done

**Review by kyle1morel — APPROVED** [review]

**Pull request merged**
