### PR TITLE
Update submitted applications page

### PR DESCRIPTION
**Pull request by wilwong89**
# Description

Updated submitted applications permit page with new card designs, wording consistencies, and utilizing new StatusPill component.
[PADS-359](https://apps.nrs.gov.bc.ca/int/jira/browse/PADS-359)

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist

- [X] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [X] I have checked that unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by slhurley** [comment]
Looking good....2 issues I see:
- The Latest Updates note is not working and also it is showing some weird code instead of a note...if there is no note it should be empty and if there is one it should show.
- Required Permits that show should no longer be hyperlinked (or appear to be a hyperlink)
- Under Required Permits, it says "We are investigating...." when empty but what if there is nothing left to investigate?  (Perhaps a UX question)

**Comment by wilwong89** [comment]
> Looking good....2 issues I see:
> 
> * The Latest Updates note is not working and also it is showing some weird code instead of a note...if there is no note it should be empty and if there is one it should show.
> * Required Permits that show should no longer be hyperlinked (or appear to be a hyperlink)
> * Under Required Permits, it says "We are investigating...." when empty but what if there is nothing left to investigate?  (Perhaps a UX question)

* Note fixed. Some temporary placeholder slipped though.
* Appearance of link removed
* Will need UX to chime in on this one. Not sure how to proceed.

**Comment by naixin-zhangbc** [comment]
Looking good! I'll confirm with Navigators on what to display when there's nothing to investigate and get back to you in a bit. Here are a few other issues:

- When there's no updates, the Latest updates in the card should display "No updates at the moment"
- The spacing between permit cards is missing. It should be 16 px for both the Required Permits section and the Submitted Applications section.
- Please remove the hover effects from the permits in the Required Permits section, so that it doesn't look interactive.
- Please change the "Ask a Navigator" button to "Ask my Navigator", and change the style to the secondary button style. Please let me know if you need the css.

Re: re-ordering the dropdown on Nav side. 
- For Application stage, please follow this order: Pre-submission, Application submission, Technical review, Pending decision, and Post-decision.
- For Application status, please switch "Pending client action" and "In progress".

**Comment by wilwong89** [comment]
> Looking good! I'll confirm with Navigators on what to display when there's nothing to investigate and get back to you in a bit. Here are a few other issues:
> 
> * When there's no updates, the Latest updates in the card should display "No updates at the moment"
> * The spacing between permit cards is missing. It should be 16 px for both the Required Permits section and the Submitted Applications section.
> * Please remove the hover effects from the permits in the Required Permits section, so that it doesn't look interactive.
> * Please change the "Ask a Navigator" button to "Ask my Navigator", and change the style to the secondary button style. Please let me know if you need the css.
> 
> Re: re-ordering the dropdown on Nav side.
> 
> * For Application stage, please follow this order: Pre-submission, Application submission, Technical review, Pending decision, and Post-decision.
> * For Application status, please switch "Pending client action" and "In progress". The rest looks good to me!

Changes made, now awaiting final designs of the "Required Permits" section.

**Comment by naixin-zhangbc** [comment]
Re: the empty state messaging for the Require Permits section. 
- Replace the current message with "We will update the necessary permits here as the project progresses. You may see this message while we are investigating or if no application is needed at this time."
- Show this message when NO permits are in "Pre-submission", OR when NONE of the "Pre-submission" permits' Needed field is "Yes".

**Comment by naixin-zhangbc** [comment]
Please make this additional change. Change the empty state message for the Submitted Applications section from "You will see your permit applications here once submitted" to "We will update your submitted applications here".

This change will mitigate user confusion. Captured this problem while reviewing another ticket. The old message doesn't consider the situation when Props submit an intake form, they may have already submitted applications.

**Review by kyle1morel — APPROVED** [review]

**Comment by kyle1morel** [comment]
Can be merged once sign off given by UX.

**Pull request merged**
